---
title: "TCR vs Ab"
author: "Tom Whalley"
date: "13 January 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(alakazam)
library(readr)
library(RColorBrewer)
library(tidyr)
```

```{r read data, message = FALSE, warning=FALSE}

read_glob <- function(directory){
  files <- list.files(directory, full.names = T)
  
  data <- lapply(files, read_csv)
  data <- do.call("rbind", data)
  
  data$X1 <- NULL
  
  return(data)
}

tcr <- read_glob("data/tcr/csvs/")
ab  <- read_glob("data/antibody/csvs/")

tcr$origin <- "TCR"
ab$origin  <- "Ab"
```

## Metadata

```{r summary dataset}
combined <- rbind(tcr, ab)

blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )

#count unique occurences of tcr and anitbody
combined %>%
  group_by(origin) %>%
  summarise(count = n_distinct(Pdb)) %>%
  ggplot(., aes(x="", y=count, fill=origin))+
  geom_bar(width = 1, stat = "identity")+
  coord_polar("y", start=0)+
  blank_theme+
  theme(axis.text.x=element_blank())+
  scale_fill_brewer(palette = "Set1")
  
```

```{r contacts}

#light == alpha
#heavy == beta

combined %>%
     mutate(donor_chain = replace(donor_chain, donor_chain == "tcra", "light")) %>% 
     mutate(donor_chain = replace(donor_chain, donor_chain == "tcrb", "heavy")) -> combined

#outright number of non-unique contacts
combined %>%
  group_by(donor_chain, origin) %>%
  tally() -> non_unique

combined %>%
  group_by(donor_chain, origin, donor_residue, Pdb) %>%
  count(donor_residue) %>%
  group_by(donor_chain, origin) %>%
  tally() -> unique

unique$status <- "unique"
non_unique$status <- "non-unique"

ncont <- rbind(unique, non_unique)

ggplot(ncont, aes(x="", y=n, fill=donor_chain))+
  geom_bar(width = 1, stat = "identity",  position = position_fill())+
  coord_polar("y", start=0)+
  blank_theme+
  theme(axis.text.x=element_blank())+
  scale_fill_brewer(palette = "Set1")+
  facet_grid(origin ~ status)+
  theme(strip.text.y = element_text(angle = 360))+
  labs(fill="Donor chain")+
  ggtitle("Number of contacts made by immunoreceptor chain")
  
```

```{r residues}
combined %>%
  group_by(donor_chain, origin, donor_residue, donor_loop) %>%
  count(donor_residue) %>%
  ggplot(., aes(x=donor_residue, y=n, fill=origin))+
  geom_bar(stat="identity")+
  facet_grid(donor_chain ~ donor_loop, scales="free")+
  theme_classic()+
  scale_fill_brewer(palette = "Set1")
  
```
```{r number of unique contacters}
combined %>%
  distinct(donor_chain, origin, donor_residue, donor_loop, Pdb) %>%
  group_by(donor_chain, origin, donor_loop, Pdb) %>%
  tally() %>%
  ggplot(., aes(x=n, fill=donor_loop))+
  geom_density(alpha=0.6)+
  facet_wrap(origin ~ donor_chain)+
  theme_classic()

combined %>%
  distinct(donor_chain, origin, donor_residue, donor_loop, Pdb) %>%
  group_by(donor_chain, origin, donor_loop, Pdb) %>%
  tally() %>%
  filter(donor_loop == "CDR3")%>%
  ggplot(., aes(x=n, fill=donor_loop))+
  geom_histogram()+
  facet_wrap(origin ~ donor_chain, scales = "free_y")+
  theme_classic()
```

```{r trend}
combined %>%
  distinct(donor_chain, origin, donor_residue, donor_loop, Pdb) %>%
  group_by(donor_chain, origin, donor_loop, Pdb) %>%
  tally() %>%
  spread(donor_chain, n) %>%
  replace_na(list(heavy = 0, light = 0)) %>%
  ggplot(., aes(x=heavy, y=light, colour = donor_loop))+
  geom_point()+
  theme_classic()+
  facet_grid(origin ~ donor_loop)+
  theme(legend.position = "none")

combined %>%
  distinct(donor_chain, origin, donor_residue, donor_loop, Pdb) %>%
  group_by(donor_chain, origin, donor_loop, Pdb) %>%
  tally() %>%
  spread(donor_chain, n) %>%
  replace_na(list(heavy = 0, light = 0)) %>%
  ggplot(., aes(x=heavy, y=light))+
  geom_hex(bins = 30)+
  scale_fill_continuous(type = "viridis")+
  theme_classic()+
  facet_grid(origin ~ donor_loop)+
  theme(legend.position = "none")

combined %>%
  distinct(donor_chain, origin, donor_residue, donor_loop, Pdb) %>%
  group_by(donor_chain, origin, donor_loop, Pdb) %>%
  tally() %>%
  spread(donor_chain, n) %>%
  replace_na(list(heavy = 0, light = 0)) %>%
  ggplot(., aes(x=heavy, y=light))+
  geom_hex()+
  scale_fill_continuous(type = "viridis")+
  theme_classic()
```

```{r sc}
sc    <- read_csv("sc_scores.csv")
sc    <- sc[sc$sc != "None",]
sc$sc <- as.numeric(sc$sc)
sc    <- na.omit(sc)

ggplot(sc, aes(x=sc, fill=origin))+
  geom_density(alpha=0.8)+
  theme_classic()+
  scale_fill_brewer(palette = "Set1")+
  xlim(c(0,1))

```

```{r contact vs sc}

```
